name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 14.17.0

jobs:
  eslint:
    runs-on: ubuntu-latest #name of docker-image
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run lint

